# Sourcery Configuration
# Focus code review on application code, scripts, and tests
#
# Template projects use docs/maintainers/ for process docs
# (dev-infra uses admin/ instead)

ignore:
  - docs/maintainers/**   # Process docs (planning, feedback, decisions)
  - tmp/**                # Temporary files (handoff docs, scratch)
  - .cursor/**            # AI workflow commands and rules (not code)
