# Sourcery Configuration
# Ignore process documentation to focus code review on actual code
#
# Template projects use docs/maintainers/ for process docs
# (dev-infra uses admin/ instead)

ignore:
  - docs/maintainers/**   # Process docs (planning, feedback, decisions)
  - tmp/**                # Temporary files (handoff docs, scratch)
