# .github/workflows/ci-branch.yml
name: CI (branch)
on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quick-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - run: npm run lint
      - run: npm test -- --ci --reporters=default
      - run: npm run build
